# Generated by Django 4.2.3 on 2023-08-09 05:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100, unique=True)),
                ('songs_description', models.CharField(max_length=100)),
                ('song_image', models.ImageField(unique=True, upload_to='song-media')),
                ('song_price', models.IntegerField(default=0)),
                ('recent_song', models.DateField(default=datetime.datetime(2023, 8, 9, 5, 44, 23, 926431))),
                ('slug', models.SlugField(default='')),
                ('artist_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Songs',
                'verbose_name_plural': 'Songs',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuser_image', models.ImageField(default='', upload_to='song-media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
