# Generated by Django 4.2.3 on 2023-08-14 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songtrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='song_packages',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('DIAMOND', 'Diamond'), ('SILVER', 'Silver')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='songs',
            name='recent_song',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 10, 9, 28, 964799)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
