# Generated by Django 4.2 on 2023-08-23 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songtrade', '0002_songs_song_packages_alter_songs_recent_song_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='recent_song',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 11, 24, 36, 377629)),
        ),
    ]
