# Generated by Django 4.2 on 2023-08-23 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songtrade', '0005_alter_songs_recent_song_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='recent_song',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 12, 2, 51, 109310)),
        ),
        migrations.AlterField(
            model_name='songs',
            name='song_packages',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('DIAMOND', 'Diamond'), ('SILVER', 'Silver')], default='GOLD', max_length=10),
        ),
    ]
